mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('photos/', include("photo.urls")),
]  
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from . import views

app_name = "photos"

urlpatterns = [
    path("", views.list, name="list"),
    path("create/", views.create, name="create"),
    path("<int:id>/", views.detail, name="detail"),
    path("<int:id>/update/", views.update, name="update"),
    path("<int:id>/delete/", views.delete, name="delete"),
    path("<int:id>/comment/",views.comment, name="comment"),
    
    
]

photo/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.
class Photo(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # image = models.ImageField(blank=True)
    image = ProcessedImageField(
                upload_to = "photo/image",
                processors = [ResizeToFill(150,150)],
                format = 'JPEG',
                options={"quality":90}
        )
    
    def __str__(self):
        return self.title
        
class Comment(models.Model):
    photo = models.ForeignKey(Photo, on_delete=models.CASCADE)
    content = models.TextField()
    
    
    def __str__(self):
        return self.content

photo/views.py
from django.shortcuts import render, redirect
from .models import Photo, Comment

# Create your views here.
def list(request):
    photos = Photo.objects.all()
    return render(request, "photo/list.html", {"photos":photos})
    
def create(request):
    if request.method == "POST":
        #POST방식으로 들어왔을 때
        title = request.POST.get("title")
        content = request.POST.get("content")
        image = request.FILES.get("image")
        
        Photo.objects.create(title=title, content=content, image=image)
        
        return redirect("photos:list")
        
    else:
        #GET방식으로 들어왔을 때
        return render(request,"photo/create.html")
        
def detail(request,id):
    photo = Photo.objects.get(id=id)
    
    return render(request,"photo/detail.html", {"photo":photo})

def update(request,id):
    photo = Photo.objects.get(id=id)
    if request.method == "POST":
        title = request.POST.get("title")
        content = request.POST.get("content")
        photo.title = title
        photo.content = content
        
        photo.save()
        
        return redirect("photos:detail",id)
        # return render(request,"photo/detail.html")
        
    else:
        return render(request, "photo/update.html", {"photo":photo})
        
def delete(request,id):
    photo = Photo.objects.get(id=id)
    photo.delete()
    return redirect("photos:list")
    
def comment(request,id):
    photo = Photo.objects.get(id=id)
    content = request.POST.get("content")
    Comment.objects.create(photo=photo, content=content)
    
    return redirect('photos:detail',id)
    

photo/templates/photo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'base.css' %}" type="text/css" />
    <link rel="shortcut icon" href="{% static 'a.jpg' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>
    <ul>
        <!--<li><a href="/photos/list">홈으로가기</a></li>-->
        <li><a href="{% url 'photos:list' %}">홈으로가기</a></li>
        <li><a href="{% url 'photos:create' %}">글작성하기</a></li>
    </ul>
    {% block bb %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>

photo/templates/photo/create.html
{% extends 'photo/base.html' %}
{% block bb %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="title"/>
        <input type="text" name="content"/>
        <input type="file" name="image" accept="image/*"/>
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}

photo/templates/photo/detail.html
{% extends 'photo/base.html' %}
{% block bb %}
    <h1>{{photo.title}}</h1>
    <h3>{{photo.content}}</h3>
    {% if photo.image %}
        <img src="{{photo.image.url}}" alt="{{photo.image}}"></img>
    {% endif %}
    <p>{{photo.created_at}}</p>
    <p>{{photo.updated_at}}</p>
    <a href="{% url 'photos:update' photo.id %}">수정하기</a>
    <a href="{% url 'photos:delete' photo.id %}">삭제하기</a>
    
    <form action="{% url 'photos:comment' photo.id %}", method="post">
        {% csrf_token %}    
        <input type="text" name="content"/>
        <input type="submit" value="Submit"/>
    </form>
    
    {% for comment in photo.comment_set.all %}
        <p>{{comment.content}}</p>
    {% endfor %}
    
{% endblock %}

photo/templates/photo/list.html
{% extends 'photo/base.html' %}
{% block bb %}
    <div class="container">
        <div class="row">
            {% for photo in photos %}
                <div class="card col-3" style="width: 18rem;">
                  {% if photo.image %}
                      <img src="{{photo.image.url}}" alt="{{photo.image}}" class="card-img-top">
                  {% endif %}
                  <div class="card-body">
                    <h5 class="card-title">{{photo.title}}</h5>
                    <p class="card-text">{{photo.content}}</p>
                    <a href="{% url 'photos:detail' photo.id%}" class="btn btn-primary">글보기</a>
                  </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

photo/templates/photo/update.html
{% extends 'photo/base.html' %}
{% block bb %}
    <form method="post">
        {% csrf_token %}
        <input type="text" name="title" value="{{photo.title}}"/>
        <input type="text" name="content" value="{{photo.content}}"/>
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}